[".config/alacritty/themes/catppuccin"]
  type = "archive"
  url = "https://github.com/catppuccin/alacritty/archive/master.tar.gz"
  exact = true
  stripComponents = 1

[".tmux/plugins/tpm"]
  type = "archive"
  url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
  exact = true
  stripComponents = 1

