# Alacritty Catppuccin theme
[".config/alacritty/themes/catppuccin"]
  type = "archive"
  url = "https://github.com/catppuccin/alacritty/archive/master.tar.gz"
  exact = true
  stripComponents = 1

# Chemacs2
[".config/emacs"]
  type = "archive"
  url = "https://github.com/plexus/chemacs2/archive/master.tar.gz"
  exact = false
  stripComponents = 1

# JetBrains Mono Nerd Font
[".fonts/JetBrainsMonoNF"]
  type = "archive"
  url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip"
  exact = true

# Roboto Mono Nerd Font
[".fonts/RobotoMonoNF"]
  type = "archive"
  url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/RobotoMono.zip"
  exact = true

# Tmux plugin manager
[".tmux/plugins/tpm"]
  type = "archive"
  url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
  exact = true
  stripComponents = 1

