[font]
size = 11.5

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
opacity = 0.8

[window.padding]
x = 7
y = 7

[general]
import = [
  "~/.config/alacritty/themes/catppuccin/catppuccin-mocha.toml",
]
